// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID        uuid.UUID
	Name      string
	UserID    uuid.UUID
	Createdat time.Time
	Updatedat time.Time
}

type Currency struct {
	ID        uuid.UUID
	Name      string
	Code      string
	Createdat time.Time
	Updatedat time.Time
}

type Transaction struct {
	ID         uuid.UUID
	CurrencyID uuid.UUID
	CategoryID uuid.UUID
	Amount     string
	Date       time.Time
	UserID     uuid.UUID
	Createdat  time.Time
	Updatedat  time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	Createdat time.Time
	Updatedat time.Time
}
