version: "3.9"

services:
  app:
    image: mickeys0105/golang-transaction:transactionapi
    container_name: golang_app
    command: >
      sh -c "app"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15.2
    container_name: postgres_db
    volumes:
      - transaction-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  transaction-data: