FROM golang:1.21-alpine

RUN go install github.com/pressly/goose/v3/cmd/goose@v3.17.0 && \
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.25.0 && \
    go install github.com/swaggo/swag/cmd/swag@latest
