basePath: /api/v1
definitions:
  models.UserRequestParams:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.UserResponseParams:
    properties:
      token:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a sample transactions server.
  termsOfService: http://swagger.io/terms/
  title: Transaction API
  version: "1.0"
paths:
  /users/:
    post:
      consumes:
      - application/json
      description: create by json User
      parameters:
      - description: Add User
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/models.UserRequestParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponseParams'
      summary: Create a user
      tags:
      - Auth
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
